"use client";

import type { ReactNode } from "react";

import Button from "@/components/Button";

interface ArrayFieldEditorProps<T> {
  label: string;
  items: readonly T[];
  /** Stable per-row keys (generated by the caller), parallel to `items`. */
  ids: readonly string[];
  onAdd: () => void;
  onRemove: (index: number) => void;
  /** Pass to enable up/down reordering (e.g. reproduction steps). */
  onMove?: (index: number, direction: "up" | "down") => void;
  renderRow: (item: T, index: number) => ReactNode;
  addLabel?: string;
  disabled?: boolean;
  className?: string;
}

/**
 * Generic add/remove(/reorder) row editor shared by FindingForm's
 * locations / reproductionSteps / references arrays. Mirrors the row
 * management pattern already used inline in DomainForm's surveyItems.
 */
export default function ArrayFieldEditor<T>({
  label,
  items,
  ids,
  onAdd,
  onRemove,
  onMove,
  renderRow,
  addLabel,
  disabled = false,
  className = "",
}: ArrayFieldEditorProps<T>) {
  return (
    <div className={`mb-6 ${className}`}>
      <div className="mb-2 text-sm font-medium text-light-text">{label}</div>
      <div className="space-y-2">
        {items.map((item, index) => (
          <div className="flex items-start gap-2" key={ids[index] ?? index}>
            {onMove && (
              <div className="flex flex-col gap-1 pt-2 text-medium-text">
                <button
                  type="button"
                  onClick={() => onMove(index, "up")}
                  disabled={disabled || index === 0}
                  className="leading-none hover:text-light-text disabled:opacity-30"
                  aria-label="上に移動"
                >
                  ↑
                </button>
                <button
                  type="button"
                  onClick={() => onMove(index, "down")}
                  disabled={disabled || index === items.length - 1}
                  className="leading-none hover:text-light-text disabled:opacity-30"
                  aria-label="下に移動"
                >
                  ↓
                </button>
              </div>
            )}
            <div className="flex-1">{renderRow(item, index)}</div>
            <Button
              type="button"
              variant="danger"
              outline
              size="small"
              onClick={() => onRemove(index)}
              disabled={disabled}
            >
              削除
            </Button>
          </div>
        ))}
      </div>
      <Button
        type="button"
        variant="primary"
        outline
        size="small"
        className="mt-3"
        onClick={onAdd}
        disabled={disabled}
      >
        {addLabel ?? `${label}を追加`}
      </Button>
    </div>
  );
}
